default[:repmgr][:base_uri] = 'http://www.repmgr.org/download'
default[:repmgr][:version] = '1.2.0'
default[:repmgr][:build_dir] = '/var/cache/repmgr'
# TODO: RHEL based packages
default[:repmgr][:packages][:pg_dev] = 'postgresql-server-dev-9.1'
default[:repmgr][:packages][:dependencies] = %w(libxslt1-dev libpam0g-dev libedit-dev libpq-dev)
default[:repmgr][:repmgrd_bin] = '/usr/bin/repmgrd'
default[:repmgr][:repmgr_bin] = '/usr/bin/repmgr'
default[:repmgr][:config_file_path] = '/etc/repmgr/repmgr.conf'
default[:repmgr][:cluster_name] = 'an_cluster'
default[:repmgr][:wal_files] = 100 # 5000 suggested for heavy writes
default[:repmgr][:system_user] = 'postgres'
default[:repmgr][:replication][:role] = 'master'
default[:repmgr][:replication][:wal_level] = 'hot_standby'
default[:repmgr][:replication][:archive_command] = '/bin/true'
default[:repmgr][:replication][:archive_timeout] = 60
default[:repmgr][:replication][:max_senders] = 5
default[:repmgr][:replication][:keep_segments] = 128
default[:repmgr][:replication][:streaming_delay] = -1
default[:repmgr][:replication][:listen_addresses] = '*'
default[:repmgr][:replication][:user] = 'replication_user'
default[:repmgr][:replication][:database] = 'replication_db'
default[:repmgr][:replication][:standby_feedback] = true
